# Generated by Django 5.0.6 on 2024-07-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('student_attendance', models.BooleanField()),
                ('end_datetime', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_datetime', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rescheduling', models.BooleanField()),
                ('request_reason', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('recurring_amount', models.IntegerField()),
                ('original_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.lessonrequest'),
        ),
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_description', models.CharField(max_length=255)),
                ('recurring_amount', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
