# Generated by Django 5.0.6 on 2024-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_lessonrequest_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='end_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
