# Generated by Django 5.0.6 on 2024-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_lessonrequest_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='end_datetime',
            field=models.DateTimeField(default=1),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='is_rescheduling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='recurring_amount',
            field=models.IntegerField(default=False),
        ),
    ]
