# Generated by Django 5.0.6 on 2024-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_lessonrequest_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
