# Generated by Django 5.0.6 on 2024-07-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_lesson_student_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_rescheduling',
        ),
        migrations.RemoveField(
            model_name='lessonrequest',
            name='original_lesson',
        ),
        migrations.CreateModel(
            name='ReschedulingRequest',
            fields=[
                ('rescheduling_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('request_reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescheduling_requests', to='scheduling.lesson')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
