# Generated by Django 5.0.6 on 2024-07-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_lesson_is_rescheduled_lesson_rescheduled_to'),
        ('users', '0008_rename_date_of_invite_invite_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('other', 'Other')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='OtherEvent',
        ),
    ]
