# Generated by Django 5.0.6 on 2024-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_calendarevent_delete_otherevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
