# Generated by Django 5.0.6 on 2024-06-29 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='invite',
            name='message',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_information',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_information',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='invite',
            name='messages_sent',
            field=models.TextField(default=None, max_length=2000, verbose_name='content of messages sent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='extra_student_info',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='extra / optional student information'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_teacher_info',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='extra / optional teacher information'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter a valid grade level between 1 and 12.')], verbose_name='grade level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\s?\\d{1,14}(\\s?\\d{1,13})?$', 'Enter a valid contact number with country code.')], verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}-\\d{2}$', 'Enter a valid date in YYYY-MM-DD format.')], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Enter a valid first name.')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Enter a valid last name.')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{6,}$', 'Password must have at least 6 characters, a special character, a number, and a capital letter.')], verbose_name='password'),
        ),
    ]
