# Generated by Django 5.0.6 on 2024-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_token_expiry',
            new_name='password_reset_token_created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
