# Generated by Django 5.0.6 on 2024-07-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_password_reset_token_expiry_user_password_reset_token_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='date_of_invite',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='invite_status',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='messages_sent',
        ),
        migrations.AddField(
            model_name='invite',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='invite',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.student'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='users.teacher'),
        ),
    ]
