# Generated by Django 5.0.6 on 2024-07-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
