# Generated by Django 5.0.6 on 2024-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_notificationconfig_lesson_reminder_1hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='lesson_reminder_1hr',
            field=models.BooleanField(default=True),
        ),
    ]
